package com.dev.ecommerce.model;
// Generated Jul 27, 2019 7:43:45 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * App generated by hbm2java
 */
@Entity
@Table(name = "app"
)
public class App implements java.io.Serializable {


    private Integer id;
    private String code;
    private String name;
    private Set<Books> bookses = new HashSet<Books>(0);
    private Set<Bags> bagses = new HashSet<Bags>(0);
    private Set<Users> userses = new HashSet<Users>(0);
    private Set<Clothes> clotheses = new HashSet<Clothes>(0);

    public App() {
    }

    public App(String code, String name, Set<Books> bookses, Set<Bags> bagses, Set<Users> userses, Set<Clothes> clotheses) {
        this.code = code;
        this.name = name;
        this.bookses = bookses;
        this.bagses = bagses;
        this.userses = userses;
        this.clotheses = clotheses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "code", length = 45)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "name", length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "app")
    public Set<Books> getBookses() {
        return this.bookses;
    }

    public void setBookses(Set<Books> bookses) {
        this.bookses = bookses;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "app")
    public Set<Bags> getBagses() {
        return this.bagses;
    }

    public void setBagses(Set<Bags> bagses) {
        this.bagses = bagses;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "app")
    public Set<Users> getUserses() {
        return this.userses;
    }

    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "app")
    public Set<Clothes> getClotheses() {
        return this.clotheses;
    }

    public void setClotheses(Set<Clothes> clotheses) {
        this.clotheses = clotheses;
    }


}


