package com.dev.ecommerce.model;
// Generated Jul 27, 2019 7:43:45 AM by Hibernate Tools 3.2.2.GA


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "orders"
)
public class Orders implements Serializable {


    private Integer id;
    private Users users;
    private Date creationDate;
    private Date eta;
    private Date deliveryDate;
    private String status;
    private Integer productTotal;
    private Integer deliveryCharges;
    private Integer orderTotal;
    private Serializable products;

    public Orders() {
    }


    public Orders(Users users) {
        this.users = users;
    }

    public Orders(Users users, Date creationDate, Date eta, Date deliveryDate, String status, Integer productTotal, Integer deliveryCharges, Integer orderTotal, Serializable products) {
        this.users = users;
        this.creationDate = creationDate;
        this.eta = eta;
        this.deliveryDate = deliveryDate;
        this.status = status;
        this.productTotal = productTotal;
        this.deliveryCharges = deliveryCharges;
        this.orderTotal = orderTotal;
        this.products = products;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "users_id", nullable = false)
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "creation_date", length = 10)
    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "eta", length = 10)
    public Date getEta() {
        return this.eta;
    }

    public void setEta(Date eta) {
        this.eta = eta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "delivery_date", length = 10)
    public Date getDeliveryDate() {
        return this.deliveryDate;
    }

    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }

    @Column(name = "status", length = 20)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "product_total")
    public Integer getProductTotal() {
        return this.productTotal;
    }

    public void setProductTotal(Integer productTotal) {
        this.productTotal = productTotal;
    }

    @Column(name = "delivery_charges")
    public Integer getDeliveryCharges() {
        return this.deliveryCharges;
    }

    public void setDeliveryCharges(Integer deliveryCharges) {
        this.deliveryCharges = deliveryCharges;
    }

    @Column(name = "order_total")
    public Integer getOrderTotal() {
        return this.orderTotal;
    }

    public void setOrderTotal(Integer orderTotal) {
        this.orderTotal = orderTotal;
    }

    @Column(name = "products")
    public Serializable getProducts() {
        return this.products;
    }

    public void setProducts(Serializable products) {
        this.products = products;
    }


}


