package com.dev.ecommerce.model;
// Generated Jul 27, 2019 7:43:45 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsersSecurityDetails generated by hbm2java
 */
@Entity
@Table(name = "users_security_details"
)
public class UsersSecurityDetails implements java.io.Serializable {


    private Integer id;
    private Users users;
    private String provider;
    private String token;

    public UsersSecurityDetails() {
    }


    public UsersSecurityDetails(String provider) {
        this.provider = provider;
    }

    public UsersSecurityDetails(Users users, String provider, String token) {
        this.users = users;
        this.provider = provider;
        this.token = token;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "users_id")
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @Column(name = "provider", nullable = false, length = 40)
    public String getProvider() {
        return this.provider;
    }

    public void setProvider(String provider) {
        this.provider = provider;
    }

    @Column(name = "token", length = 300)
    public String getToken() {
        return this.token;
    }

    public void setToken(String token) {
        this.token = token;
    }


}


